min_word_length = 3

# Only check these tags. Empty means check everything.
# Example: ["comment", "string"]
# include_tags = []

dictionaries = [
    "en_us",
    "ru",
]
words = [
    "AIHR",
    "AccessToken",
    "BACKEND",
    "BatchType",
    "COPY",
    "Config",
    "ContextVar",
    "Dishka",
    "ETL",
    "FastAPI",
    "Install",
    "LinkedIn",
    "MyCustomError",
    "OAUTH",
    "ORM",
    "ProviderClient",
    "ProviderClientError",
    "ProviderError",
    "ProviderFK",
    "RefreshToken",
    "Repo",
    "Summarizer",
    "SummarizerClient",
    "SummaryResult",
    "TG",
    "TODO",
    "UoW",
    "Url",
    "ValueError",
    "WS",
    "asyncpg",
    "celery_setup",
    "clangd",
    "cmakelang",
    "cmakelint",
    "codelldb",
    "config",
    "cpplint",
    "cssls",
    "cssmodules",
    "debugpy",
    "di",
    "dishka",
    "enum",
    "etc",
    "fastapi",
    "filters",
    "hadolint",
    "http",
    "install",
    "kwargs",
    "lspconfig",
    "markdownlint",
    "neovim",
    "noqa",
    "oxfmt",
    "pcs",
    "pyright",
    "pytest",
    "repo",
    "reportArgumentType",
    "reportAttributeAccessIssue",
    "reportCallIssue",
    "reportIndexIssue",
    "reportMissingTypeStubs",
    "reportPrivateUsage",
    "reportUnknownArgumentType",
    "reportUnknownMemberType",
    "reportUnknownVariableType",
    "reportUnusedImport",
    "shellcheck",
    "shfmt",
    "softtabstop",
    "sqlfluff",
    "stylua",
    "taplo",
    "uv",
    "vtsls",
    "zuban",
    "zubanls",
    "БД",
    "алиасу",
    "алиасы",
    "батч",
    "дефолтный",
    "имитируем",
    "конфиг",
    "логгер",
    "маппинг",
    "оркестрация",
    "пайплайн",
    "пайплайна",
    "пайплайне",
    "проавайдера",
    "пробрасывается",
    "репозиторий",
    "саммарайзера",
    "саммари",
    "саммаризации",
    "суммаризатора",
    "суммаризаторов",
    "суммаризации",
    "фейк",
    "фейковые",
    "фэйк",
    "фэйки",
    "фэйковой",
    "фэйковый",
    "фэйковым",
    "фэйковыми",
    "хелпер",
]
include_tags = [
    "comment",
    "string",
    "identifier.definition",
]
